### ISSUE TITLE
anonymous is missing the Overall/UploadPlugins permission

### ISSUE THREAD

**Issue by xbeta** [opscode-cookbooks/jenkins#282]
so we are logging as 'anonymous' to install plugins? that doesn't sound right to us. If we grant this access to anonymous, it would be everyone, not just this chef cookbook.

I think we should 1) use the CLI tool to change the permission, 2) install all the plugins listed 3) remove that permission

```bash
---- Begin output of java -jar /var/chef/cache/jenkins-cli.jar -s http://localhost:8080 install-plugin android-lint  ----
STDOUT:
STDERR: hudson.security.AccessDeniedException2: anonymous is missing the Overall/UploadPlugins permission
	at hudson.security.ACL.checkPermission(ACL.java:57)
	at hudson.model.Node.checkPermission(Node.java:417)
	at hudson.cli.InstallPluginCommand.run(InstallPluginCommand.java:74)
	at hudson.cli.CLICommand.main(CLICommand.java:236)
	at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:310)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:290)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:249)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:328)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
	at hudson.remoting.InterceptingExecutorService$2.call(InterceptingExecutorService.java:95)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by schisamo** [comment]
Closing this as the issue appears to be resolved.
