### ISSUE TITLE
Plugin provider doesn't seem to be honoring requested version

### ISSUE THREAD

**Issue by dpetzel** [opscode-cookbooks/jenkins#297]
I ran into https://github.com/opscode-cookbooks/jenkins/issues/292 indirectly today. This issue is not to report the malformed version error, it just so happens hitting hit made me see this issue.

In my cookbook I'm requesting to install version `1.14`, which is re-enforced in the output below where it shows the compiled resource. However based on the exception its trying to install `1.16-5`.

This was running v2.2.1 of this cookbook

It should install the version I am requesting.

```
[2014-12-06T15:52:36-08:00] INFO: Processing jenkins_plugin[ghprb] action install (cookbook::_plugins line 31)

================================================================================
Error executing action `install` on resource 'jenkins_plugin[ghprb]'
================================================================================


ArgumentError
-------------
Malformed version number string 1.16-5


Cookbook Trace:
---------------
/var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:145:in `new'
/var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:145:in `block in <class:JenkinsPlugin>'


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/cookbook/recipes/_plugins.rb

 31:   jenkins_plugin plugin[:id] do
 32:     version plugin[:version]
 33:     source plugin[:source]
 34:     install_deps false
 35:     notifies :execute, 'jenkins_command[safe-restart]'
 36:   end
 37: end



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/cookbook/recipes/_plugins.rb:31:in `block in from_file'

jenkins_plugin("ghprb") do
  action :install
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name "cookbook"
  recipe_name "_plugins"
  version "1.14"
end



[2014-12-06T15:52:36-08:00] INFO: Running queued delayed notifications before re-raising exception
[2014-12-06T15:52:36-08:00] ERROR: Running exception handlers
[2014-12-06T15:52:36-08:00] ERROR: Exception handlers complete
[2014-12-06T15:52:36-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-12-06T15:52:36-08:00] INFO: Sending resource update report (run-id: 47b50301-913e-4c63-86ff-ce12839af818)
[2014-12-06T15:52:37-08:00] ERROR: jenkins_plugin[ghprb] (cookbook::_plugins line 31) had an error: ArgumentError: Malformed version number string 1.16-5

```

**Comment by schisamo** [comment]
This should have been fixed in version `v2.2.2` of this cookbook. Namely in this commit:
https://github.com/opscode-cookbooks/jenkins/commit/1e9e591ca4ff5f38efd7a600afec3e0cad7d722f
