### ISSUE TITLE
runit_service[jenkins] cannot be found

### ISSUE THREAD

**Issue by kylegibson** [opscode-cookbooks/jenkins#316]
Chef: 11.16.4
Jenkins (cookbook): 2.2.2
runit (cookbook): 1.5.14 (latest) and 1.5.0 (oldest supported). Did not test other version.
Using chef-solo
Install method: WAR

```
[2015-01-21T16:08:43-05:00] WARN: Here we go with the runit service
[2015-01-21T16:08:43-05:00] INFO: Running queued delayed notifications before re-raising exception
[2015-01-21T16:08:43-05:00] ERROR: Running exception handlers
[2015-01-21T16:08:43-05:00] ERROR: Exception handlers complete
[2015-01-21T16:08:43-05:00] FATAL: Stacktrace dumped to /tmp/chef-solo/cache/chef-stacktrace.out
[2015-01-21T16:08:43-05:00] ERROR: resource remote_file[/var/lib/jenkins/jenkins.war] is configured to notify resource runit_service[jenkins] with action restart, but runit_service[jenkins] cannot be found in the resource collection. remote_file[/var/lib/jenkins/jenkins.war] is defined in /tmp/chef-solo/cookbooks/jenkins/recipes/_master_war.rb:59:in `from_file'
```

Stack trace:

```
Generated at 2015-01-21 16:08:43 -0500
Chef::Exceptions::ResourceNotFound: resource remote_file[/var/lib/jenkins/jenkins.war] is configured to notify resource runit_service[jenkins] with action restart, but runit_service[jenkins] cannot be found in the resource collection. remote_file[/var/lib/jenkins/jenkins.war] is defined in /tmp/chef-solo/cookbooks/jenkins/recipes/_master_war.rb:59:in `from_file'

/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource_collection.rb:123:in `lookup'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource_collection.rb:241:in `find_resource_by_string'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource_collection.rb:147:in `block in find'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource_collection.rb:142:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource_collection.rb:142:in `find'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource.rb:66:in `fix_resource_reference'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource.rb:55:in `resolve_resource_reference'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource.rb:452:in `block in resolve_notification_references'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource.rb:452:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource.rb:452:in `resolve_notification_references'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/runner.rb:76:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource_collection.rb:90:in `block in each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource_collection.rb:89:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/resource_collection.rb:89:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/runner.rb:75:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:345:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:431:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:207:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/client.rb:207:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/solo.rb:226:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/solo.rb:218:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application/solo.rb:218:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/application.rb:55:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:23:in `load'
/usr/bin/chef-solo:23:in `<main>'
```

**Comment by schisamo** [comment]
@kylegibson Any chance you can try a more recent version of Chef?

**Comment by schisamo** [comment]
Closing this for now since there has been no response from the author. Feel free to reopen.
