### ISSUE TITLE
Unable to restart Jenkins if Jenkins runs on port other than 8080

### ISSUE THREAD

**Issue by isuftin** [opscode-cookbooks/jenkins#319]
- Problem: I have a Tomcat instance running on port 8080 and as a result would like to run Jenkins on port  >= 8081. I am setting this on a base CentOS 6.6 image. The only attribute I've set is: default["jenkins"]["master"]["port"] = "8081". The recipes "jenkins::java" and "jenkins::master" run fine. I then have a recipe that creates the chef user.  The recipe may be seen [here](https://github.com/isuftin/cookbook-jenkins/blob/master/recipes/create_chef_user.rb). When the recipe runs, the Jenkins service gets restarted. The restart listens for Jenkins to be running on port 8080. Jenkins is, in fact, running on port 8081 so the converge fails. This works fine if I do not set an alternate port to run Jenkins on. **This actually seems to work fine if I set the attribute in .kitchen.yml but not in my default attributes file I've also tried setting the attributes file precedence to normal and override with no success.**

- Source: https://github.com/isuftin/cookbook-jenkins

- Command: kitchen converge vmware **or** kitchen converge vbox

- Expectation: Jenkins service to restart by listening to port 8081 instead of 8080

- What actually happened: Jenkins restart listens to incorrect port (8080 instead of 8081)

- OS: CentOS 6.6 (on MacOS 10.9 host)
- Cookbook Version: 2.2.2
- Ruby Version: ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin12.0]
- Rubygems Version: 2.4.4
- Chef Version: chef-client on guest: 12.0.3, ChefDK 0.3.6 on host
- env:
    ```
HOSTNAME=alt-port-cida-centos-66-vmware.vagrantup.com
SELINUX_ROLE_REQUESTED=
TERM=screen
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=192.168.53.1 60929 22
SELINUX_USE_CURRENT_RANGE=
SSH_TTY=/dev/pts/0
USER=vagrant
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/vagrant
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/vagrant/bin
PWD=/home/vagrant
LANG=en_US.UTF-8
SELINUX_LEVEL_REQUESTED=
HISTCONTROL=ignoredups
SHLVL=1
HOME=/home/vagrant
LOGNAME=vagrant
SSH_CONNECTION=192.168.53.1 60929 192.168.53.138 22
LESSOPEN=||/usr/bin/lesspipe.sh %s
G_BROKEN_FILENAMES=1
_=/bin/env
    ```
- Backtrace:
    ``` 
       Recipe: cida_jenkins::create_chef_user


           ================================================================================
           Error executing action `create` on resource 'jenkins_user[chef-jenkins]'
           ================================================================================

           Jenkins::Helper::JenkinsNotReady
           --------------------------------
           The Jenkins master at `http://localhost:8080' did not become ready within 60
           seconds. On large Jenkins instances, you may need to increase the timeout to
           240 seconds. Alternatively, Jenkins may have failed to start.
           Jenkins can fail to start if:

             - a configuration file is invalid
             - a plugin is only partially installed
             - a plugin's dependencies are not installed

           If this problem persists, check your Jenkins log files.

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:360:in `rescue in wait_until_ready!'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:340:in `wait_until_ready!'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:61:in `executor'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/user.rb:138:in `current_user'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/user.rb:74:in `load_current_resource'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cida_jenkins/recipes/create_chef_user.rb

            15: jenkins_user 'chef-jenkins' do
            16:   full_name   'Chef Jenkins Client'
            17:   email 'chef-jenkins@chef.owiclient.org'
            18:   public_keys [chef_jenkins_public_key]
            19:   action :create
            20:   #notifies :execute, "jenkins_script[setup authentication]", :immediately
            21:   #notifies :execute, "jenkins_command[clear-queue]", :immediately
            22: end
            23:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/cida_jenkins/recipes/create_chef_user.rb:15:in `from_file'

           jenkins_user("chef-jenkins") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_user
             cookbook_name "cida_jenkins"
             recipe_name "create_chef_user"
             full_name "Chef Jenkins Client"
             email "chef-jenkins@chef.owiclient.org"
             public_keys ["ssh-rsa AAAA ... chef-jenkins@chef.owicloud.org"]
             id "chef-jenkins"
           end


       Running handlers:
       [2015-01-25T06:47:06+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-01-25T06:47:06+00:00] ERROR: Exception handlers complete
       [2015-01-25T06:47:06+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 64.808764968 seconds
       [2015-01-25T06:47:06+00:00] ERROR: jenkins_user[chef-jenkins] (cida_jenkins::create_chef_user line 15) had an error: Jenkins::Helper::JenkinsNotReady: The Jenkins master at `http://localhost:8080' did not become ready within 60
       seconds. On large Jenkins instances, you may need to increase the timeout to
       240 seconds. Alternatively, Jenkins may have failed to start.
       Jenkins can fail to start if:

         - a configuration file is invalid
         - a plugin is only partially installed
         - a plugin's dependencies are not installed

       If this problem persists, check your Jenkins log files.

       [2015-01-25T06:47:06+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
 ```

**Comment by isuftin** [comment]
It seems like no matter where I set my attributes and regardless of the precedence, the master attribute file wipes out my settings and sets ["jenkins"]["master"]["port"] to the hard-coded 8080

**Comment by isuftin** [comment]
Figured it out. Employing the wrapper attribute method recomputes the attributes that jenkins::master does in the jenkins cookbook. Adding the following to my default.rb attributes file does the job: 

```
default['jenkins']['master']['port'] = 8081
default['jenkins']['master']['endpoint'] = "http://#{node['jenkins']['master']['host']}:#{node['jenkins']['master']['port']}"
```

I was reminded of issues like this from https://www.chef.io/blog/2013/12/03/doing-wrapper-cookbooks-right/

**Comment by gebrouwe** [comment]
Thanx for sharing! I am running Jenkins through a reverse proxy on port 49001 and ran into the same problem.

**Comment by radiomix** [comment]
I do have a similar issue, running jenkins on port 9090 with this beeing in my wrapper cookbook:
```
#
# Cookbook Name:: jenkins-wrapper
# Recipe:: default
#

# supermarket cookbooks needed
include_recipe 'jenkins::java'
include_recipe 'jenkins::master'

# install via package
node.default['jenkins']['master']['install_method'] = 'package'

# set the port
node.default['jenkins']['master']['port'] = '9090'

# The timeout passed to the runit cookbook's service resource to wait
# until Jenkins is up and running before using jenkins cli
node.default['jenkins']['master']['runit']['sv_timeout'] = 60

#################################################
# plugins
################################################

# install matrix with  dependencies
jenkins_plugin 'matrix-auth'

# install github-oauth with  dependencies
jenkins_plugin 'github-oauth'

# install credentials with dependencies
jenkins_plugin 'credentials'
```

The error message gets the attribute `sv_timeout` I configured correctly but not the `port`.
