### ISSUE TITLE
junkins_plugin ContentLengthMismatch for remote url

### ISSUE THREAD

**Issue by fletchowns** [opscode-cookbooks/jenkins#322]
I have plugins uploaded to S3 and I'm running into this quite frequently. Not sure if it's an issue with S3 or what, I was able to curl the URL and download it on my machine, and the sha256 matches the [official one](http://updates.jenkins-ci.org/download/plugins/git-client/1.12.0/git-client.hpi). Other remote_file uses in this chef run that hit this same bucket don't have any issue. This is running on a local VirtualBox VM via Vagrant. Any ideas?

```
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mycorp-jenkins/recipes/jenkins_plugins.rb
==> default:
==> default:  15:       jenkins_plugin plugin["name"] do
==> default:  16:               source "#{node['mycorp-jenkins']['plugin_source_url']}/#{plugin['name']}/#{plugin['version']}/#{plugin['name']}.hpi"
==> default:  17:               version plugin["version"]
==> default:
==> default:  18:               install_deps false
==> default:  19:       end
==> default:  20: end
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mycorp-jenkins/recipes/jenkins_plugins.rb:15:in `block in from_file'
==> default:
==> default:
==> default: jenkins_plugin("git-client") do
==> default:   action :install
==> default:   retries 0
==> default:   retry_delay 2
==> default:   guard_interpreter :default
==> default:   cookbook_name :"mycorp-jenkins"
==> default:   recipe_name "jenkins_plugins"
==> default:   source "https://s3-us-west-1.amazonaws.com/my-bucket/jenkins-plugins/git-client/1.12.0/git-client.hpi"
==> default:   version "1.12.0"
==> default: end
==> default:
==> default:
==> default:
==> default: [2015-01-27T22:31:00+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-01-27T22:31:00+00:00] DEBUG: Re-raising exception: Chef::Exceptions::ContentLengthMismatch - jenkins_plugin[git-client] (mycorp-jenkins:
:jenkins_plugins line 15) had an error: Chef::Exceptions::ContentLengthMismatch: remote_file[/var/chef/cache/jenkins-cli.jar] (dynamically defined) had an error
: Chef::Exceptions::ContentLengthMismatch: Response body length 179864 does not match HTTP Content-Length header 751490.
==> default: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/http/validate_content_length.rb:102:in `validate'
==> default:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/http/validate_content_length.rb:60:in `handle_stream_complete'
==> default:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/http.rb:236:in `block in apply_stream_complete_middleware'
==> default:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/http.rb:234:in `each'
==> default:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/http.rb:234:in `inject'
==> default:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/http.rb:234:in `apply_stream_complete_middleware'
==> default:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/http.rb:174:in `block in streaming_request'
==> default:   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/http/basic_client.rb:74:in `block in request'
```

**Comment by fletchowns** [comment]
I'm getting the same error with http

**Comment by fletchowns** [comment]
Same error with the official http://updates.jenkins-ci.org/download/plugins

**Comment by fletchowns** [comment]
I'm able to reproduce the issue outside of my network on an EC2 instance

**Comment by fletchowns** [comment]
Seems to download just fine when using `Chef::HTTP::Simple` manually:
```
uri = URI('https://s3-us-west-1.amazonaws.com/my-bucket/jenkins-plugins/git-client/1.12.0/git-client.hpi')
http = Chef::HTTP::Simple.new(uri.host)
tmp_file = http.streaming_request(uri.to_s)
```

**Comment by juliandunn** [comment]
I am not able to reproduce this with your version of Chef.

```
[ec2-user@ip-172-31-22-112 ~]$ chef-apply -s
remote_file '/tmp/whee' do
  source 'https://updates.jenkins-ci.org/download/plugins/git-client/1.12.0/git-client.hpi'
end
^D
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * remote_file[/tmp/whee] action create
    - create new file /tmp/whee
    - update content in file /tmp/whee from none to f585fa
    (new content is binary, diff output suppressed)
[ec2-user@ip-172-31-22-112 ~]$ chef-apply --version
Chef: 11.16.2
```

**Comment by lamont-granquist** [comment]
A gist of the full output of `chef-client -l debug` showing all the debug header information and everything else associated with the resource might help, along with all the logging that all the Chef::HTTP middleware does.  Getting tcpdump logs of the stream might show that a RST is coming back from s3 or something like that indicating a bad TCP teardown.  Its possible that the server is gzip compressing the file and it has a smaller size in the payload but the server failed to indicate gzip compression (but since the server is s3 i'd think we'd have a plague of bug reports--which we don't have).  I tried replicating this last time and similarly failed to replicate the issue.

**Comment by fletchowns** [comment]
Whoops, I wasn't going far enough back in the exception. It looks like the download of git-client.hpi is actually working fine. The trouble seems to be when it grabs https://jenkins.mycorp.com//jnlpJars/jenkins-cli.jar. Looks like maybe because it's being gzipped but the content-type and content-length headers are not reflecting that?

Here's a gist of the debug output: https://gist.github.com/fletchowns/e6ae51aa20eaddc775ee

**Comment by lamont-granquist** [comment]
s3 isn't sending back gzip headers and we're doing the noop gzip inflator which means its not gzipped.  and the number of bytes downloaded this time is different - 605848 vs 179864 - which is not consistent with gzipped content length vs ungzipped content length.

about all i can think of is to take out any sysctl settings that you have around tcp/ip tuning and to turn off all the possible tcp offload settings...

ethtool --offload  eth0  rx off  tx off sg off tso off ufo off gso off gro off lro off rxvlan off txvlan off rxhash off

(untested command, no idea if all those options are supported on your box)

**Comment by fletchowns** [comment]
Thanks Lamont! Couldn't get that command to work (and don't know much about ethtool) but now that I know the actual file download it's failing on I was able to reproduce it with curl.

Downloading jenkins-cli.jar through nginx reverse proxy:
```
[vagrant@jenkins ~]$ curl -versbose https://jenkins.mycorp.com//jnlpJars/jenkins-cli.jar -o jenkins-cli.jar
* About to connect() to jenkins.mycorp.com port 443 (#0)
*   Trying 127.0.1.1... connected
* Connected to jenkins.mycorp.com (127.0.1.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_DHE_RSA_WITH_AES_256_CBC_SHA
> GET //jnlpJars/jenkins-cli.jar HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: jenkins.mycorp.com
> Accept: */*
> Referer: rsbose
>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 200 OK
< Server: nginx/1.6.2
< Date: Wed, 28 Jan 2015 18:36:26 GMT
< Content-Type: application/java-archive
< Content-Length: 751490
< Connection: keep-alive
< Content-Disposition: attachment; filename=jenkins-cli.jar
< Last-Modified: Wed, 28 Jan 2015 03:52:35 GMT
< Expires: Wed, 28 Jan 2015 03:52:35 GMT
< Accept-Ranges: bytes
< X-Content-Type-Options: nosniff
<
{ [data not shown]
* transfer closed with 276719 bytes remaining to read
 63  733k   63  463k    0     0  4278k      0 --:--:-- --:--:-- --:--:-- 16.7M* Closing connection #0

curl: (18) transfer closed with 276719 bytes remaining to read
```

And the nginx error log shows this:
```
2015/01/28 18:42:02 [crit] 1005#0: *21 open() "/opt/nginx-1.6.2/proxy_temp/0/01/0000000010" failed (13: Permission denied) while reading upstream, client: 127.0.1.1, server: jenkins, request: "GET //jnlpJars/jenkins-cli.jar HTTP/1.1", upstream: "http://127.0.0.1:8080//jnlpJars/jenkins-cli.jar", host: "jenkins.mycorp.com", referrer: "rsbose"
```

The permissions to `/opt/nginx-1.6.2/proxy_temp` looked ok but it turned out that an unrelated script was mucking with the permissions of the parent directory.

Thanks so much for your time, really appreciate it. I'll go ahead and close this one out.
