### ISSUE TITLE
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method hudson.plugins.sshslaves.SSHLauncher

### ISSUE THREAD

**Issue by Sauraus** [opscode-cookbooks/jenkins#338]
Related to: https://github.com/opscode-cookbooks/jenkins/issues/282

The following error is thrown with Jenkins 1.594 when trying to add a Slave to a server that has security enable on it and ```node.run_state[:jenkins_private_key] = jenkins_keys['private_key']
``` is set in the recipe before executing ```jenkins_ssh_slave node['hostname'] do```. Without the run_state & private_key the error returned is anonymous is not permitted to run script.

```
[2015-04-07T16:21:32-07:00] ERROR: jenkins_ssh_slave[ssh_slave_box] (jenkins-wrapper::slave line 168) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
---- Begin output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://jenkins-server-fqdn:8080 -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20150407-18234-18wx7ba ----
STDOUT: 
STDERR: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method hudson.plugins.sshslaves.SSHLauncher#<init>.
Cannot resolve which method to invoke for [class java.lang.String, class java.lang.Integer, null, null, null, null, null] due to overlapping prototypes between:
	[class java.lang.String, int, interface com.cloudbees.plugins.credentials.common.StandardUsernameCredentials, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String]
	[class java.lang.String, int, interface com.cloudbees.jenkins.plugins.sshcredentials.SSHUser, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String]
	at groovy.lang.MetaClassImpl.chooseMostSpecificParams(MetaClassImpl.java:2922)
	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:2875)
	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:2816)
	at groovy.lang.MetaClassImpl.createConstructorSite(MetaClassImpl.java:3065)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:75)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at RemoteClass.run(RemoteClass:64)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:266)
	at groovy.lang.GroovyShell.run(GroovyShell.java:517)
	at hudson.cli.GroovyCommand.run(GroovyCommand.java:94)
	at hudson.cli.CLICommand.main(CLICommand.java:237)
	at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:326)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:301)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:260)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
	at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
	at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
---- End output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://jenkins-server-fqdn:8080 -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20150407-18234-18wx7ba ----
Ran "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://jenkins-server-fqdn:8080 -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20150407-18234-18wx7ba returned 255
[2015-04-07T16:21:32-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by schisamo** [comment]
@Sauraus What version of the Jenkins cookbook are you using?

**Comment by schisamo** [comment]
@Sauraus Could you also share your `jenkins_ssh_slave` resource definition from your recipe?

**Comment by Sauraus** [comment]
I got this error when the ```node.run_state[:jenkins_private_key] = jenkins_keys['private_key'] ``` was in a ruby block, moving it out resolved that problem but now I have the error ```STDERR: hudson.security.AccessDeniedException2: anonymous is missing the Credentials/Update permission``` when I try to run anything...

PS. It would be really helpful if the documentation had an example of how to do a wrapper cookbook properly for jenkins master & slaves.

**Comment by schisamo** [comment]
@Sauraus The fixture cookbooks contain plenty of examples:
https://github.com/opscode-cookbooks/jenkins/blob/master/test/fixtures/cookbooks/authentication/recipes/private_key.rb#L18-L53

**Comment by Sauraus** [comment]
Interesting :) so I am running the latest jenkins cookbook 2.3.0 and Jenkis 1.612 and something is going very wrong with the private_key::

```begin
  keys_bag = search("#{node['jenkins']['master']['hostname']}_keys", '*:*')
  jenkins_keys = Chef::EncryptedDataBagItem.load("#{node['jenkins']['master']['hostname']}_keys", "jenkins_keys", secret)
  node.run_state[:jenkins_private_key] = jenkins_keys['private_key']
rescue Net::HTTPServerException => ne
  if ne.message =~ /^404/
    Chef::Log.warn "No DATA BAG found for #{node['jenkins']['master']['hostname']}"
    require 'net/ssh'

    key = OpenSSL::PKey::RSA.new(4096)
    private_key = key.to_pem
    public_key  = "#{key.ssh_type} #{[key.to_blob].pack('m0')} jenkins@#{node[:hostname]}"

    keys_bag = Chef::DataBag.new
    keys_bag.name("#{node['jenkins']['master']['hostname']}_keys")
    keys_bag.create

    jenkins_keys = {
        "id" => "jenkins_keys",
        "private_key" => private_key,
        "public_key" => public_key
    }

    databag_items = Chef::EncryptedDataBagItem.encrypt_data_bag_item(jenkins_keys, secret)

    databag_item = Chef::DataBagItem.new
    databag_item.data_bag("#{node['jenkins']['master']['hostname']}_keys")
    databag_item.raw_data = databag_items
    databag_item.save
    node.run_state[:jenkins_private_key] = jenkins_keys['private_key']
  else
    raise ne
  end
end

# Create the Jenkins user private credentials
jenkins_private_key_credentials 'jenkins' do
  private_key jenkins_keys['private_key']
end```

The above code results in the following error being thrown by the recipe::

```    * file[/var/chef/cache/jenkins-key] action create (up to date)
    
    ================================================================================
    Error executing action `create` on resource 'jenkins_private_key_credentials[jenkins]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '255'
    ---- Begin output of "/usr/lib/jvm/java-1.7.0/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://my_awesome_fqdn_here:8080 groovy /tmp/groovy20150515-28650-1m645n0 ----
    STDOUT: 
    STDERR: hudson.security.AccessDeniedException2: anonymous is missing the Overall/RunScripts permission```

What am I missing? Why is the recipe executing the 'create' on resource as anonymous and not as jenkins user?

**Comment by Sauraus** [comment]
```jenkins_ssh_slave node['hostname'] do
  description "Jenkins slave on host #{node['hostname']}"
  remote_fs node['wrapper']['workspace']
  executors node['wrapper']['executors']
  availability 'always'
  labels node['diw-jenkins']['labels']
  host node['fqdn']
  user 'jenkins'
  credentials 'jenkins'
end```

**Comment by schisamo** [comment]
@Sauraus Is the public side of that private key already attached to a Jenkins user? If not it needs to be. For example:
https://github.com/opscode-cookbooks/jenkins/blob/master/test/fixtures/cookbooks/authentication/recipes/private_key.rb#L21-L25

**Comment by dasomx77** [comment]
I am encountering the same exact problem and I have the same file showed in the url @schisamo has provided:
include_recipe 'jenkins::master'

require 'net/ssh'
key = OpenSSL::PKey::RSA.new(4096)
private_key = key.to_pem
public_key = "#{key.ssh_type} #{[key.to_blob].pack('m0')}"

node.run_state['user_pass'] = Vault_Decrypter_PlatformIntegrity_getSecret node['jenkins']['user_pass_name'] do
  notifies :run, "ruby_block[get_password]", :immediately
end

ruby_block 'get_password' do
  block do
    require 'json'
    username_and_password = JSON.parse(node.run_state['user_pass'].unencrypted_file)
    node.run_state['password'] = username_and_password['password']
    node.run_state['username'] = username_and_password['username']
  end
end

node.run_state[:jenkins_private_key] = private_key


jenkins_user 'chef' do
  action :delete
end

jenkins_user 'chef' do
  full_name 'Chef User'
  email 'platformintegrity2@careerbuilder.com'
  password lazy { node.run_state['password'] }
  public_keys [public_key]
end

jenkins_user 'platformintegrity' do
  full_name 'Platform Integrity'
  email 'platformintegrity2@careerbuilder.com'
  password lazy { node.run_state['password'] }
  public_keys [public_key]
end

jenkins_script 'setup authentication' do
  command <<-EOH.gsub(/^ {4}/, '')
    import jenkins.model
    def instance = Jenkins.getInstance()

    import hudson.security.*
    def realm = new HudsonPrivateSecurityRealm(false)
    instance.setSecurityRealm(realm)

    def strategy = new hudson.security.FullControlOnceLoggedInAuthorizationStrategy()
    instance.setAuthorizationStrategy(strategy)

    instance.save()
  EOH
end

it is still not working and giving me the exact same error--- help!

**Comment by Sauraus** [comment]
Ok this is weird but after reading this https://issues.jenkins-ci.org/browse/JENKINS-22346 I was looking into this more and what I found was that as long as the chef created user has an email address for a user that exists in AD, then this will all work just fine.
