### ISSUE TITLE
2.3.0 authentication for CLI - I'm failing

### ISSUE THREAD

**Issue by jblaine** [opscode-cookbooks/jenkins#360]
I've read the README and one of the recently closed issues on this and am still making no progress.

My CLI commands are still running as anonymous and not with my private key and matching user, so I must not be understanding something, and I've been getting nowhere. Any thoughts from another set of eyes would be super welcome at this point. I'll gladly submit a documentation patch as necessary, assuming I'm not just being dense here.

rcf-jenkins/recipes/master.rb says in full:
```
node.run_state[:jenkins_private_key] = <<EOF
-----BEGIN RSA PRIVATE KEY-----
MIIEoQIBAAKCAQEA+DRCrtPi5/E7rNP...blah blah...
-----END RSA PRIVATE KEY-----
EOF

include_recipe 'jenkins::java'
include_recipe 'jenkins::master'

# For now, I have corporate AD running through manual configuration that is
# not rolled back into Chef. The web UI works fine as 'jblaine' + my corp AD password.

jenkins_user 'jblaine' do
  # The named account above MUST EXIST IN corporate AD.
  public_keys ['ssh-rsa AAAAB3NzaC...blah blah...MSlFxYMKipB1Jw== jenkins.our.org']
end

jenkins_plugin "scm-api"
jenkins_plugin "git-client"
jenkins_plugin "git"
jenkins_plugin 'subversion'
jenkins_plugin 'cvs'
jenkins_plugin 'jira'
jenkins_plugin 'greenballs'
```

Failure shows usage of the **anonymous** user (which we obviously have intentionally restricted), not user jblaine:
```
...
    ================================================================================
    Error executing action `create` on resource 'jenkins_user[jblaine]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '255'
    ---- Begin output of "/usr/lib/jvm/java-1.7.0/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://jenkins.mitre.org:8080 groovy /tmp/groovy20150518-6266-1mfxdr7 ----
    STDOUT:
    STDERR: hudson.security.AccessDeniedException2: anonymous is missing the Overall/RunScripts permission
        at hudson.security.ACL.checkPermission(ACL.java:63)
        at hudson.model.Node.checkPermission(Node.java:441)
        at hudson.cli.GroovyCommand.run(GroovyCommand.java:74)
        at hudson.cli.CLICommand.main(CLICommand.java:237)
        at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:326)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:301)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:260)
        at hudson.remoting.UserRequest.perform(UserRequest.java:121)
        at hudson.remoting.UserRequest.perform(UserRequest.java:49)
        at hudson.remoting.Request$2.run(Request.java:325)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
        at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
        at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
        at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    ---- End output of "/usr/lib/jvm/java-1.7.0/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://jenkins.mitre.org:8080 groovy /tmp/groovy20150518-6266-1mfxdr7 ----
    Ran "/usr/lib/jvm/java-1.7.0/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://jenkins.mitre.org:8080 groovy /tmp/groovy20150518-6266-1mfxdr7 returned 255

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:84:in `execute!'
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:137:in `groovy!'
    /var/chef/cache/cookbooks/jenkins/libraries/user.rb:95:in `block (2 levels) in <class:JenkinsUser>'
    /var/chef/cache/cookbooks/jenkins/libraries/user.rb:94:in `block in <class:JenkinsUser>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/rcf-jenkins/recipes/master.rb

     34: jenkins_user 'jblaine' do
     35:   # The named account above MUST EXIST IN corporate AD.
     36:   public_keys ['ssh-rsa AAAAB3NzaC...blah blah...lFxYMKipB1Jw== jenkins.our.org']
     37: end
     38:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/rcf-jenkins/recipes/master.rb:34:in `from_file'

    jenkins_user("jblaine") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :jenkins_user
      cookbook_name "rcf-jenkins"
      recipe_name "master"
      public_keys ["ssh-rsa AAAAB3NzaC1...blah blah... Jw== jenkins.our.org"]
      id "jblaine"
    end

```

**Comment by jblaine** [comment]
Oh, and, thanks very much for releasing this CB. This saved us many hours!

**Comment by schisamo** [comment]
@jblaine What version of Jenkins are you using? You could also give the the executor username/password support a go that was added in https://github.com/opscode-cookbooks/jenkins/pull/355:

```
node.run_state[:jenkins_username]
node.run_state[:jenkins_password]
```

**Comment by jblaine** [comment]
@schisamo 1.614.

As a workaround to make progress, I gave Anonymous the Overall/RunScript privilege, though that's obviously not correct long-term.

My reading of #355 is that the specified user and password would need to exist in our chosen non-Jenkins-local authentication backend. That's why we targeted this SSH keypair as a perfect solution. Since we use the active-directory plugin, I guess I'd have to create a service account for this purpose so I'm not storing my personal work password in a Chef recipe (or vault, etc).

**Comment by schisamo** [comment]
@jblaine You def want to use a service account. Here at Chef we use GitHub OAuth for authn/authz. Here is the snippet from our wrapper cookbook that configures everything:

```ruby
################################################################################
# Configure Authentication
################################################################################
jenkins_users = encrypted_data_bag_item_for_environment('jenkins', 'users')

node.run_state[:jenkins_private_key] = jenkins_users['chef-jenkins']['private_key'] # ~FC001

# Create a Jenkins user for Chef to authenitcate with for confiugration
# activities
jenkins_user 'chef-jenkins' do
  full_name 'Chef Jenkins User'
  public_keys [jenkins_users['chef-jenkins']['public_key']]
end

# Enable GitHub OAuth as the authenitcation backend
github_oauth_creds = encrypted_data_bag_item_for_environment('jenkins', 'github-oauth')

jenkins_script 'enable-github-auth' do
  command <<-GROOVY.flush
    import jenkins.model.*
    import hudson.security.*
    import org.jenkinsci.plugins.*
    jenkins = jenkins.model.Jenkins.getInstance()
    githubRealm = new GithubSecurityRealm(
      'https://github.com',
      'https://api.github.com',
      '#{github_oauth_creds['client-id']}',
      '#{github_oauth_creds['client-secret']}'
    )
    jenkins.setSecurityRealm(githubRealm)
    strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    jenkins.setAuthorizationStrategy(strategy)
    jenkins.save()
  GROOVY
end
```

I'm beginning to wonder if using the AD/LDAP plugin has some edge cases.

**Comment by adrianmoisey** [comment]
@schisamo is that using the github-oauth plugin?

**Comment by schisamo** [comment]
@adrianmoisey It sure is. Here is the exact versions of all the plugins we use:

```ruby
################################################################################
# Plugins
################################################################################
plugins = {
  'greenballs'               => '1.14',
  'credentials'              => '1.22',
  'ssh-credentials'          => '1.11',
  'scm-api'                  => '0.2',
  'git-client'               => '1.17.1',
  'git'                      => '2.3.5',
  'envinject'                => '1.91.2',
  'parameterized-trigger'    => '2.26',
  'copyartifact'             => '1.35.1',
  'conditional-buildstep'    => '1.3.3',
  'token-macro'              => '1.10',
  'email-ext'                => '2.40.2',
  'run-condition'            => '1.0',
  'hipchat'                  => '0.1.9',
  'audit-trail'              => '2.1',
  'downstream-buildview'     => '1.9',
  'promoted-builds'          => '2.21',
  'copy-to-slave'            => '1.4.4',
  'disk-usage'               => '0.25',
  'monitoring'               => '1.56.0',
  # DO NOT UPGRADE THIS PLUGIN. IT'S HELLA BROKEN ON NEWER VERSIONS
  'rebuild'                  => '1.20',
  'postbuild-task'           => '1.8',
  'ws-cleanup'               => '0.25',
  'xshell'                   => '0.9',
  'parameter-separator'      => '0.8',
  'jenkins-multijob-plugin'  => '1.16',
  'dashboard-view'           => '2.9.4',
  'jquery'                   => '1.11.2-0',
  'jquery-ui'                => '1.0.2',
  'mailer'                   => '1.15',
  'github-api'               => '1.67',
  'github-oauth'             => '0.20',
  'build-monitor-plugin'     => '1.6+build.142',
  'build-failure-analyzer'   => '1.13.0',
  'claim'                    => '2.7',
  'test-stability'           => '1.0',
  'zentimestamp'             => '4.0',
  'build-user-vars-plugin'   => '1.4',
}

plugins.each_with_index do |(plugin_name, plugin_version), index|
  jenkins_plugin plugin_name do
    version plugin_version
    install_deps false
    action  :install
    # only restart on the final plugin
    if index == (plugins.size - 1)
      notifies :restart, 'runit_service[jenkins]', :immediately
    end
  end
end
```

**Comment by adrianmoisey** [comment]
Whoa, that's cool. You should publish more of your wrapper cookbooks (or just the parts that are sharable).

**Comment by adrianmoisey** [comment]
Also, your comments have the incorrect spelling of 'authenticate' :)

**Comment by jblaine** [comment]
I can't reproduce this anymore :(

We're now using the [https://wiki.jenkins-ci.org/display/JENKINS/Role+Strategy+Plugin](Role Strategy Plugin) and I've got an Anonymous role defined with no privileges assigned. Installing new plugins via `jenkins_plugin` works via the defined run_state private key coupled with a public key assigned to an AD service account.
