### ISSUE TITLE
Java Array out of bounds Exceptions from jenkins_plugins resource

### ISSUE THREAD

**Issue by dasomx77** [opscode-cookbooks/jenkins#367]
Hey there, I am currently writing a wrapper around the jenkins cookbook. Right from the get go, in my default recipe I have included the jenkins:master recipe if the value in attribute node['jenkins']['master']['home'] doesn't exist; I then process to go through an array of plugin I want to install the very firs tone being token-macro and I get the error below (tried on an actual machine and on kitchen):

---- Begin output of "/usr/lib/jvm/java-1.7.0/bin/java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://default-centos-66:8080 -p : install-plugin /tmp/kitchen/cache/token-macro-1.10.plugin -name token-macro  ----
       STDOUT: 
       STDERR: java.lang.ArrayIndexOutOfBoundsException: 0
       	at hudson.cli.CLI.connectViaCliPort(CLI.java:185)
       	at hudson.cli.CLI.<init>(CLI.java:128)
       	at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
       	at hudson.cli.CLI._main(CLI.java:479)
       	at hudson.cli.CLI.main(CLI.java:390)

The lines that actually trigger the error:

if (!File.exist?("#{node['jenkins']['master']['home']}"))
  include_recipe 'packer_cookbook::install_jenkins'
end

node['jenkins']['plugins'].each do |plugin|
  if !Dir.exist?(node['jenkins']['jenkins_cli_location'])
    node.override['jenkins']['jenkins_cli_location'] = '/tmp/kitchen/cache/jenkins-cli.jar'
  end
  jenkins_plugin plugin do
    lazy { action [:install, :enable] }
    not_if {
      Chef::Log.info("Logging in as user: chef")
      Chef::Log.info("Checking if plugin #{plugin} is installed..")
      command1 = `java -jar #{node['jenkins']['jenkins_cli_location']} -s http://#{node['jenkins']['master']['host']}:#{node['jenkins']['master']['port']}/ who-am-i`
      command2 = `java -jar #{node['jenkins']['jenkins_cli_location']} -s http://#{node['jenkins']['master']['host']}:#{node['jenkins']['master']['port']}/ list-plugins`
       Chef::Log.info("#{command1.to_s}")
       Chef::Log.info("#{command2.to_s}")
       Chef::Log.info("Plugin #{plugin} installed?: #{command2.to_s.include?(plugin)}")
      command2.to_s.include?(plugin)
    }
  end
end

it seems to be a problem with hudson cli but I do not have a way to double check and trace the reason of this error. I get the same error as well when login into every node running this cookbook and running the exact command. Alongside, I am using the war installation of jenkins and have a different recipe that installs java, here are the java configurations:

[vagrant@default-centos-66 ~]$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.3.el6_6-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

I would really appreciate anyone's help...

**Comment by dasomx77** [comment]
Fixed the issue, this was due to a proxy variable enabled that added the -p parameter to the jenkins-cli argument list.
