### ISSUE TITLE
can't modify frozen String

### ISSUE THREAD

**Issue by gimler** [opscode-cookbooks/jenkins#371]
The setup works great after update to jenkins (2.3.1) i get a error

```
RuntimeError
------------
can't modify frozen String


Cookbook Trace:
---------------
/var/lib/monsoon/repos/eventticketing/jenkins/chef/cookbooks/jenkins/libraries/_helper.rb:140:in `gsub!'
/var/lib/monsoon/repos/eventticketing/jenkins/chef/cookbooks/jenkins/libraries/_helper.rb:140:in `convert_to_groovy'
/var/lib/monsoon/repos/eventticketing/jenkins/chef/cookbooks/jenkins/libraries/credentials_private_key.rb:99:in `credentials_groovy'
/var/lib/monsoon/repos/eventticketing/jenkins/chef/cookbooks/jenkins/libraries/credentials.rb:117:in `block (2 levels) in <class:JenkinsCredentials>'
/var/lib/monsoon/repos/eventticketing/jenkins/chef/cookbooks/jenkins/libraries/credentials.rb:104:in `block in <class:JenkinsCredentials>'
```

my code
```
data_bag('deploy_keys').each do |project|
  jenkins_private_key_credentials project do
    description "#{project} pivate key for github access"
    private_key data_bag_item('deploy_keys', project)['private_key']
  end
end
```

i fix this changing the username from `project` to `project.dup`

**Comment by Rarian** [comment]
Just wanted to comment, that I'm running into a similar issue with the jenkins_ssh_slave LWRP.  Have not investigated at all what may be causing this after coming across this issue and _fixing_ with  `.dup`.

Code from wrapper cookbook:
```ruby
if slaves.nil?
  Chef::Log.warn('Could not find any slaves, have they escaped?') 
else
  # define the slaves launched via SSH
  slaves.each do |slave_name, slave|

    # There is an issue with this LWRP trying to alter slave_name
    # and running into issues with it being immutable/frozen.
    # At somepoint this may be fixed up stream and the .dup can
    # be removed.
    # Similar issue here: https://github.com/opscode-cookbooks/jenkins/issues/371
    jenkins_ssh_slave slave_name.dup do
      description 'Run builds as slaves'
      remote_fs   '/var/lib/jenkins'
      labels      ['executor']

      executors  slave['executors']

      # SSH specific attributes
      host        slave['fqdn']
      user        node['jenkins']['master']['user']
      credentials node['jenkins']['master']['user']
    end
  end
end
```

**Comment by Rarian** [comment]
Great! Can we get a version bump on this?

**Comment by schisamo** [comment]
We'll bump the version when we ship a new version of the cookbook. Still performing testing and merging  various fixes.
