### ISSUE TITLE
NullPointerException when cookbook reads parameters of registered Jenkins slave

### ISSUE THREAD

**Issue by ifel** [opscode-cookbooks/jenkins#378]
Background: one uses JNLP slave managed by chef, with Environment variables set.

First run of the recipe on the node is successful. At that time, the slave isn't registered yet, and the recipe registers it in Jenkins. However, all runs, when the slave is already registered fails with NPE:
```
================================================================================
    Error executing action `create` on resource 'jenkins_jnlp_slave[ci-platform-slave01]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '255'
    ---- Begin output of "/usr/lib/jvm/java/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://ci-platform-master:8080/jenkins -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20150611-23612-b9idg8 ----
    STDOUT: 
    STDERR: java.lang.NullPointerException
    ---- End output of "/usr/lib/jvm/java/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://ci-platform-master:8080/jenkins -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20150611-23612-b9idg8 ----
    Ran "/usr/lib/jvm/java/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://ci-platform-master:8080/jenkins -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20150611-23612-b9idg8 returned 255
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:84:in `execute!'
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:137:in `groovy!'
    /var/chef/cache/cookbooks/jenkins/libraries/slave.rb:315:in `current_slave'
    /var/chef/cache/cookbooks/jenkins/libraries/slave.rb:129:in `load_current_resource'
    /var/chef/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:52:in `load_current_resource'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/macys_jenkins/recipes/jnlp_slave.rb
    
      4: jenkins_jnlp_slave node['macys_jenkins']['jnlp_slave']['name'] do
      5:   description  node['macys_jenkins']['jnlp_slave']['description']
      6:   remote_fs    node['macys_jenkins']['jnlp_slave']['remote_fs']
      7:   executors    node['macys_jenkins']['jnlp_slave']['executors']
      8:   usage_mode   node['macys_jenkins']['jnlp_slave']['usage_mode']
      9:   availability node['macys_jenkins']['jnlp_slave']['availability']
     10:   labels       node['macys_jenkins']['jnlp_slave']['labels']
     11:   environment  node['macys_jenkins']['jnlp_slave']['environment']
     12:   user         node['macys_jenkins']['jnlp_slave']['user']
     13:   jvm_options  node['macys_jenkins']['jnlp_slave']['jvm_options']
     14:   
     15:   action :create
     16: end
     17: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/macys_jenkins/recipes/jnlp_slave.rb:4:in `from_file'
    
    jenkins_j_n_l_p_slave("ci-platform-slave01") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :jenkins_jnlp_slave
      cookbook_name "macys_jenkins"
      recipe_name "jnlp_slave"
      description "Jenkins slave ci-platform-slave01"
      remote_fs "/opt/jenkins_home"
      executors 10
      usage_mode "normal"
      availability "always"
      environment {"LANG"=>"en_US.UTF-8", "GEM_HOME"=>"/opt/jenkins_home/.rvm/gems/ruby-1.9.3-p551", "GEM_PATH"=>"/opt/jenkins_home/.rvm/gems/ruby-1.9.3-p551:/opt/jenkins_home/.rvm/gems/ruby-1.9.3-p551@global", "PATH"=>"/opt/jenkins_home/.rvm/gems/ruby-1.9.3-p551/bin:/opt/jenkins_home/.rvm/gems/ruby-1.9.3-p551@global/bin:/opt/jenkins_home/.rvm/rubies/ruby-1.9.3-p551/bin:/usr/local/maven-2.2.1/bin:/usr/local/ant-1.8.2/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/jenkins_home/.rvm/bin:/opt/jenkins_home/bin"}
      user "jenkins"
      slave_name "ci-platform-slave01"
    end
```

Gonna create a merge request in few minutes.

**Comment by schisamo** [comment]
Fixed in 10a665c0c5320405710297e7f7abf218669a711e.
